;;; hive-claude-sync.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(declare-function hive-claude-state-get-session "hive-claude-state")

(declare-function hive-claude-state-put-field "hive-claude-state")

(declare-function hive-mcp-swarm-hooks-register "hive-mcp-swarm-hooks")

(declare-function hive-mcp-swarm-hooks-unregister "hive-mcp-swarm-hooks")

(defun hive-claude-sync--event-matches-p (event-type target)
  "Return non-nil if EVENT-TYPE matches TARGET (with or without colon prefix)."
  (or (string-equal event-type target) (string-equal event-type (format ":%s" target))))

(defun hive-claude-sync--handle-started (agent-id event-data)
  "Handle hivemind-started: set working status."
  (hive-claude-state-put-field agent-id :status 'working)
  (hive-claude-state-put-field agent-id :current-task (plist-get event-data :task)))

(defun hive-claude-sync--handle-progress (agent-id)
  "Handle hivemind-progress: maintain working status."
  (hive-claude-state-put-field agent-id :status 'working))

(defun hive-claude-sync--handle-completed (agent-id session)
  "Handle hivemind-completed: set idle, increment counter."
  (hive-claude-state-put-field agent-id :status 'idle)
  (hive-claude-state-put-field agent-id :current-task nil)
  (hive-claude-state-put-field agent-id :tasks-completed (+ (or (plist-get session :tasks-completed) 0) 1)))

(defun hive-claude-sync--handle-error (agent-id session)
  "Handle hivemind-error: set idle, increment failures."
  (hive-claude-state-put-field agent-id :status 'idle)
  (hive-claude-state-put-field agent-id :current-task nil)
  (hive-claude-state-put-field agent-id :tasks-failed (+ (or (plist-get session :tasks-failed) 0) 1)))

(defun hive-claude-sync--handle-blocked (agent-id)
  "Handle hivemind-blocked: set blocked status."
  (hive-claude-state-put-field agent-id :status 'blocked))

(defun hive-claude-sync-sync-from-hivemind (event-data)
  "Sync session state from hivemind EVENT-DATA.\n\n   Called via hooks when hivemind receives shout events.\n   Maps agent-id to slave-id and updates status accordingly."
  (let* ((agent-id (plist-get event-data :agent-id))
        (event-type (plist-get event-data :event-type))
        (session (when agent-id
    (hive-claude-state-get-session agent-id))))
    (when session
    (if (hive-claude-sync--event-matches-p event-type "hivemind-started") (hive-claude-sync--handle-started agent-id event-data) (if (hive-claude-sync--event-matches-p event-type "hivemind-progress") (hive-claude-sync--handle-progress agent-id) (if (hive-claude-sync--event-matches-p event-type "hivemind-completed") (hive-claude-sync--handle-completed agent-id session) (if (hive-claude-sync--event-matches-p event-type "hivemind-error") (hive-claude-sync--handle-error agent-id session) (when (hive-claude-sync--event-matches-p event-type "hivemind-blocked")
    (hive-claude-sync--handle-blocked agent-id)))))))))

(defun hive-claude-sync-register-hooks-bang ()
  "Register sync-from-hivemind with the swarm hooks system.\n   Called during hive-claude addon initialization."
  (when (fboundp 'hive-mcp-swarm-hooks-register)
    (dolist (event-type '(:hivemind-started :hivemind-progress :hivemind-completed :hivemind-error :hivemind-blocked))
    (hive-mcp-swarm-hooks-register event-type #'hive-claude-sync-sync-from-hivemind))))

(defun hive-claude-sync-unregister-hooks-bang ()
  "Unregister sync hooks. Called during shutdown."
  (when (fboundp 'hive-mcp-swarm-hooks-unregister)
    (dolist (event-type '(:hivemind-started :hivemind-progress :hivemind-completed :hivemind-error :hivemind-blocked))
    (hive-mcp-swarm-hooks-unregister event-type #'hive-claude-sync-sync-from-hivemind))))

(provide 'hive-claude-sync)
;;; hive-claude-sync.el ends here
