;;; hive-claude-state.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(defvar hive-claude-state-sessions (make-hash-table :test 'equal) )

(defun hive-claude-state-get-session (slave-id)
  "Get session plist for SLAVE-ID, or nil."
  (gethash slave-id hive-claude-state-sessions))

(defun hive-claude-state-get-field (slave-id key)
  "Get KEY from session SLAVE-ID."
  (let* ((session (gethash slave-id hive-claude-state-sessions)))
    (when session
    (plist-get session key))))

(defun hive-claude-state-put-field (slave-id key value)
  "Set KEY to VALUE in session SLAVE-ID."
  (let* ((session (or (gethash slave-id hive-claude-state-sessions) '())))
    (puthash slave-id (plist-put session key value) hive-claude-state-sessions)))

(defun hive-claude-state-register-session (slave-id props)
  "Register a new session with initial PROPS plist."
  (puthash slave-id props hive-claude-state-sessions))

(defun hive-claude-state-remove-session (slave-id)
  "Remove session SLAVE-ID from registry."
  (remhash slave-id hive-claude-state-sessions))

(defun hive-claude-state-session-exists-p (slave-id)
  "Return non-nil if SLAVE-ID is registered."
  (gethash slave-id hive-claude-state-sessions))

(defun hive-claude-state-all-session-ids ()
  "Return list of all registered slave-ids."
  (hash-table-keys hive-claude-state-sessions))

(defun hive-claude-state-session-count ()
  "Return count of registered sessions."
  (hash-table-count hive-claude-state-sessions))

(defun hive-claude-state-for-each-session (callback)
  "Call CALLBACK with (slave-id session) for each registered session."
  (maphash callback hive-claude-state-sessions))

(defun hive-claude-state-clear-all ()
  "Remove all sessions. Used during shutdown."
  (clrhash hive-claude-state-sessions))

(provide 'hive-claude-state)
;;; hive-claude-state.el ends here
