;;; hive-claude-config.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(require 'clojure-elisp-runtime)

;;; Code:



(defvar hive-claude-config-claude-command "claude"
  "Path to the Claude Code CLI binary.")

(defvar hive-claude-config-prompt-mode 'bypass
  "Permission mode for spawned lings.\n   - bypass: Use --permission-mode bypassPermissions\n   - human: Forward prompts to master\n   - auto: Timer-based auto-approve")

(defvar hive-claude-config-buffer-prefix "*swarm-"
  "Prefix for swarm terminal buffer names.")

(defun hive-claude-config--permission-flag ()
  "Return the CLI flag string for the current prompt mode."
  (pcase hive-claude-config-prompt-mode
  ((quote bypass) "--permission-mode bypassPermissions")
  ('_unused "")))

(defun hive-claude-config-build-command (work-dir system-prompt-file)
  "Build the claude CLI command string.\n\n   WORK-DIR is the working directory to cd into.\n   SYSTEM-PROMPT-FILE is an optional path to a temp .md file with the prompt.\n\n   Returns a shell command string ready to send to a terminal."
  (let* ((base-cmd (format "cd %s && %s %s" (shell-quote-argument work-dir) hive-claude-config-claude-command (hive-claude-config--permission-flag))))
    (if system-prompt-file (format "%s --system-prompt %s" base-cmd (shell-quote-argument system-prompt-file)) base-cmd)))

(defun hive-claude-config-build-env (slave-id depth master-id)
  "Build process-environment additions for a Claude session.\n\n   Returns a list of KEY=VALUE strings to prepend to process-environment."
  (list (format "CLAUDE_SWARM_DEPTH=%d" depth) (format "CLAUDE_SWARM_MASTER=%s" (or master-id "direct")) (format "CLAUDE_SWARM_SLAVE_ID=%s" slave-id)))

(defun hive-claude-config-make-buffer-name (name)
  "Create a buffer name for a claude ling.\n   NAME is the human-readable ling name."
  (format "%s%s*" hive-claude-config-buffer-prefix name))

(defun hive-claude-config-write-prompt-file (content)
  "Write CONTENT to a temp file for --system-prompt flag.\n   Returns the file path."
  (let* ((prompt-file (make-temp-file "swarm-prompt-" nil ".md")))
    (with-temp-file prompt-file (insert content))
    prompt-file))

(defun hive-claude-config-build-identity-section (slave-id work-dir)
  "Build the identity preamble injected into every ling's system prompt.\n\n   This ensures lings know their exact agent ID and working directory,\n   preventing ID hallucination (Architecture > LLM behavior)."
  (format "## YOUR IDENTITY AND ENVIRONMENT (CRITICAL)\n\n**Your agent ID is: `%s`**\n**Your working directory is: `%s`**\n\nYou MUST use this EXACT ID in ALL hivemind tool calls:\n- `hivemind_shout(agent_id: \"%s\", ...)`\n- `hivemind_ask(agent_id: \"%s\", ...)`\n\nYou MUST use paths relative to your working directory or use the EXACT path above.\n- CORRECT: `src/hive_mcp/foo.clj` or `%s/src/hive_mcp/foo.clj`\n- WRONG: `/Users/...` or `/home/otheruser/...` (DO NOT hallucinate paths!)\n\nDO NOT invent your own ID. DO NOT use short names like \"ling-worker\".\nThe coordinator tracks you by this exact ID.\n\n---\n\n" slave-id work-dir slave-id slave-id work-dir))

(provide 'hive-claude-config)
;;; hive-claude-config.el ends here
